spring.application.name=candidat
server.port=8081
welcome.message= Welcome to Candidat MS

#EUREKA_Registery
spring.cloud.config.import-check.enabled=false
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

#DATA BASE_ Configuration
spring.datasource.username=Omar
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./Database/Data/Candidat;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Spring RabbitMQ
#spring.rabbitmq.host=localhost
spring.rabbitmq.host=rabbitmq

# port par défaut du protocole AMQP
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
#spring.rabbitmq.enabl

#spring config
spring.cloud.config.enabled=false
#spring.config.import=optional:configserver:http://localhost:8888
spring.config.import=optional:configserver:http://config-server:8888
logging.level.org.springframework.cloud.config=DEBUG
logging.level.org.springframework.boot.context.config=DEBUG

#spring actuator
management.endpoints.web.exposure.include=refresh

#spring keycloak
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Job_Board_Realm2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/Job_Board_Realm2